# --- C?u hình Câu a: ?oán s? ---
task.a.target_number=36
task.a.max_attempts=18

# --- C?u hình Câu b: Tính ti?n ?i?n ---
task.b.tier1_limit=100
task.b.tier1_price=1000
task.b.tier2_limit=150
task.b.tier2_price=1500
task.b.tier3_price=2000

# --- C?u hình Câu d: Database MySQL ---
db.url=jdbc:mysql://localhost:3306/java_core_db
db.username=root
db.password=123456
db.host=localhost
